#!/bin/sh -e
#
# Generate ssh server keys

KEY_TYPES="rsa ecdsa ed25519"

if [ "$(id -u -r)" -ne 0 ]; then
    echo "Must be run as root."
    exit 1
fi

snapctl stop "$SNAP_INSTANCE_NAME"
for key_type in $KEY_TYPES; do
    keyfile="$SNAP_DATA/ssh/ssh_host_${key_type}_key"
    rm -f "$keyfile"
    "$SNAP/usr/bin/ssh-keygen" -N "" -t "$key_type"  \
        -f "$keyfile" \
        -C "$SNAP_INSTANCE_NAME server key (type $key_type)"
done

echo
echo "Server public keys:"
echo
cat "$SNAP_DATA"/ssh/ssh_host_*_key.pub
snapctl start "$SNAP_INSTANCE_NAME"
