#!/bin/sh -e
#
# Generate sshd config

SSH_CONFIGS="$SNAP_DATA/ssh"
AUTHORIZED_KEYS_FILE="$SSH_CONFIGS/authorized_keys"

ssh_loglevel="${1:-INFO}"
ssh_port="${2:-2222}"
ssh_authorizedkeys="$3"

cat >"$SSH_CONFIGS/sshd_config" <<EOF
Port $ssh_port

HostKey $SSH_CONFIGS/ssh_host_rsa_key
HostKey $SSH_CONFIGS/ssh_host_ecdsa_key
HostKey $SSH_CONFIGS/ssh_host_ed25519_key

AuthorizedKeysFile $AUTHORIZED_KEYS_FILE
PasswordAuthentication no
ChallengeResponseAuthentication no
PermitRootLogin yes
AllowUsers root
AllowGroups root

LogLevel $ssh_loglevel
PidFile $SNAP_DATA/sshd.pid
ClientAliveInterval 60

PrintMotd no
PrintLastLog no

AcceptEnv LANG LC_*

Subsystem sftp $SNAP/usr/lib/openssh/sftp-server
EOF

echo "$ssh_authorizedkeys" > "$AUTHORIZED_KEYS_FILE"
