name: sshuttle-bastion
version: git
summary: OpenSSH server for use as sshuttle bastion host
description: |
  Run an OpenSSH server so that the host can be used as a sshuttle target.

  The (confined) "root" user can log in to the ssh server with authorized keys.

  The snap also contains Python which is needed for running the server-side
  script pushed by sshuttle.

  Available snap settings:

    ssh.authorizedkeys: content of the authorized keys file
    ssh.loglevel: the log devel (default: INFO)
    ssh.port: the port to run ssh on (default: 2222)

confinement: strict
grade: stable
base: core18

apps:
  sshd:
    daemon: simple
    command: usr/sbin/sshd -D -f $SNAP_DATA/ssh/sshd_config
    environment:
      LD_PRELOAD: $SNAP/usr/lib/stub_calls.so
    plugs:
      - network-bind

  regenerate-server-keys:
    command: sbin/sshd-keys-generate

parts:
  base:
    plugin: dump
    source: tree
    stage-packages:
      - openssh-server
      - python3.6

  stub-calls:
    plugin: make
    source: stub-calls
    build-packages:
      - build-essential
    artifacts:
      - stub_calls.so
    organize:
      stub_calls.so: usr/lib/stub_calls.so
    prime:
      - usr/lib/stub_calls.so
